root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "./tailwindcss -i ./static/input.css -o ./static/output.css && go build -o ./tmp/main ."
  exclude_dir = ["tmp"]
  exclude_file = ["./static/input.css"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "html", "ts", "js", "css"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
