version: '3.8'

# Extends from the base docker-compose.yml
services:
  backend:
    image: ghcr.io/oliverbutler/omo:latest # In CI will will template "latest" with the relevant SHA
    ports:
      - target: 6900
        published: 6900
        protocol: tcp
        mode: host
    environment:
      - 'TEMPORAL_HOST=temporal:7233'
      - 'DB_HOST=db'
      - 'DB_NAME=oliverbutler'
      - 'DB_USER=postgres'
      - 'DB_PORT=5432'
      - 'DB_PASSWORD=password'
      - 'BASE_URL=http://0.0.0.0:6900'
      - 'ENV=production'
    depends_on:
      - db
      - temporal
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 20
        window: 120s
