version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '6900:6900'
    environment:
      - APP_PORT=6900
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=oliverbutler
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=oliverbutler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
