version: '3.8'

services:
  db:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=oliverbutler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
