version: '3.8'

# Extends from the base docker-compose.yml
services:
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - db
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
