version: '3.8'

services:
  backend:
    image: oliverbutler/oliverbutler
    ports:
      - '6900:6900'
    environment:
      - ENV=${ENV}
      - APP_PORT=6900
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=oliverbutler
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    depends_on:
      - db
      - minio

  db:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=oliverbutler
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - '9000:9000'
      - '9001:9001'
