version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app

  db:
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    volumes:
      - ./minio_data:/data
