apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: default
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/omo/backend
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/oliverbutler/omo:2024-12-18T194447Z-b9c3be5
        ports:
        - containerPort: 6900
        env:
        - name: TEMPORAL_HOST
          value: "temporal:7233"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "oliverbutler"
        - name: DB_USER
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_PASSWORD
          value: "password"
        - name: BASE_URL
          value: "http://10.0.70.11:6900"
        - name: ENV
          value: "production"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: omo-secrets
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: omo-secrets
              key: GITHUB_CLIENT_SECRET
        readinessProbe:
          httpGet:
            path: /
            port: 6900
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 6900
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: backend-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 6900
      targetPort: 6900
      nodePort: 6900
