apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oliverbutler/omo.git
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
