apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: backend-storage
        hostPath:
          path: /home/omo/backend
          type: DirectoryOrCreate
      containers:
      - name: backend
        image: ghcr.io/oliverbutler/omo:2024-12-19T185639Z-d134666
        ports:
        - containerPort: 6900
        env:
        - name: TEMPORAL_HOST
          value: "temporal:7233"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "oliverbutler"
        - name: DB_USER
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_PASSWORD
          value: "password"
        - name: BASE_URL
          value: "https://oliverbutler.uk"
        - name: ENV
          value: "production"
        - name: ROOT_STORAGE_PATH
          value: '/mnt/storage'
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: omo-secrets
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: omo-secrets
              key: GITHUB_CLIENT_SECRET
        volumeMounts:
        - name: backend-storage
          mountPath: /mnt/storage
        readinessProbe:
          httpGet:
            path: /
            port: 6900
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 6900
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 6900
      targetPort: 6900
      nodePort: 6900
