services:
  traefik:
    image: "traefik:v3.3"
    restart: unless-stopped
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=dev@oliverbutler.uk"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend:
    image: ghcr.io/oliverbutler/omo:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6900/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`oliverbutler.uk`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=6900"
      - "traefik.http.services.backend.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.backend.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.backend.loadbalancer.healthcheck.timeout=5s"
      - "traefik.http.services.backend.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.backend.loadbalancer.sticky.cookie.name=backend_sticky"
      - "traefik.http.services.backend.loadbalancer.sticky.cookie.secure=true"
    environment:
      DB_HOST: db
      DB_NAME: oliverbutler
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      BASE_URL: https://oliverbutler.com
      ENV: production
      TEMPORAL_HOST: temporal:7233
      # AUTH_GITHUB_CLIENT_ID: TODO
      # AUTH_GITHUB_CLIENT_SECRET: TODO
      # STORAGE_ENDPOINT: https://b0bd4bf4ecaf861687a5f5a08fde654c.r2.cloudflarestorage.com
      # STORAGE_ACCESS_KEY_ID: ${STORAGE_ACCESS_KEY_ID}
      # STORAGE_SECRET_ACCESS_KEY: ${STORAGE_SECRET_ACCESS_KEY}
    depends_on:
      - db

  db:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      - POSTGRES_DB=oliverbutler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:1.25.0
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=db
    ports:
      - target: 7233
        published: 7233
        mode: host

  temporal-admin-tools:
    restart: unless-stopped
    image: temporalio/admin-tools:1.25.0-tctl-1.18.1-cli-1.0.0
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true

  temporal-ui:
    restart: unless-stopped
    image: temporalio/ui:2.30.3
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - target: 8080
        published: 7234
        mode: host
volumes:
  pgdata:
