config:
  clients:
    - url: http://10.0.0.40:3100/loki/api/v1/push

  snippets:
    extraScrapeConfigs: |
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__

serviceMonitor:
  enabled: false

tolerations:
  - effect: NoSchedule
    operator: Exists

rbac:
  create: true
  pspEnabled: false

securityContext:
  privileged: true
  runAsUser: 0
  runAsGroup: 0

extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibcontainers
    hostPath:
      path: /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v2.task/k8s.io

extraVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibcontainers
    mountPath: /var/lib/rancher/k3s/agent/containerd/io.containerd.runtime.v2.task/k8s.io
    readOnly: true
