name: Build & Deploy ðŸš€
run-name:
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Checkout code â¤µï¸
        uses: actions/checkout@v3

      - name: Set up Docker Buildx ðŸ‘·
        uses: docker/setup-buildx-action@v2

      - name: Login to Gitea Container Registry ðŸ”
        run: echo "${{ secrets.CONTAINER_REPO_TOKEN }}" | docker login git.oliverbutler.uk -u ${{ gitea.actor }} --password-stdin

      - name: Generate unique tag
        id: tag
        run: |
          echo "UNIQUE_TAG=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image ðŸ’¨
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            git.oliverbutler.uk/olly/omo:${{ steps.tag.outputs.UNIQUE_TAG }}
            git.oliverbutler.uk/olly/omo:latest
          platforms: linux/amd64
