name: Build & Deploy ðŸš€
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Checkout code â¤µï¸
        uses: actions/checkout@v3

      - name: Set up Docker Buildx ðŸ‘·
        uses: docker/setup-buildx-action@v2

      - name: Login to Gitea Container Registry ðŸ”
        run: echo "${{ secrets.CONTAINER_REPO_TOKEN }}" | docker login git.local.oliverbutler.uk -u ${{ gitea.actor }} --password-stdin

      - name: Generate unique tag
        id: tag
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          SHA_SHORT=$(echo ${{ gitea.sha }} | cut -c1-8)
          echo "UNIQUE_TAG=${TIMESTAMP}-${SHA_SHORT}" >> $GITEA_OUTPUT

      - name: Build and push Docker image ðŸ’¨
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: git.local.oliverbutler.uk/olly/omo:${{ env.UNIQUE_TAG }}
          platforms: linux/amd64
