name: Build & Deploy 🚀
run-name:
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - name: Checkout code ⤵️
        uses: actions/checkout@v3

      - name: Set up Docker Buildx 👷
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers 💾
        uses: https://github.com/actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Gitea Container Registry 🔐
        run: echo "${{ secrets.CONTAINER_REPO_TOKEN }}" | docker login git.oliverbutler.uk -u ${{ gitea.actor }} --password-stdin

      - name: Build and push Docker image 💨
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: git.oliverbutler.uk/olly/omo:${{ github.sha }},git.oliverbutler.uk/olly/omo:latest
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache 🔄
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
