name: Deploy
run-name: ${{ gitea.actor }}'s Deployment
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Gitea Container Registry
        run: echo "${{ secrets.GITEA_TOKEN }}" | docker login git.oliverbutler.uk -u ${{ gitea.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: git.oliverbutler.uk/${{ gitea.repository }}:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show built image
        run: docker images
